version: '3.8'

services:
  data-simulator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - CORE_ENGINE_URL=${CORE_ENGINE_URL}
      - RESPONSE_SERVICE_URL=${RESPONSE_SERVICE_URL}
      - DEBUG=True
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
