services:
  - type: web
    name: utdrs-data-simulator
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME 
        value: utdrs
      - key: API_GATEWAY_URL
        value: https://utdrs-api-gateway.onrender.com
      - key: CORE_ENGINE_URL
        value: https://utdrs-core-engine.onrender.com
      - key: RESPONSE_SERVICE_URL
        value: https://response-service.onrender.com
      - key: DEBUG
        value: false
